### ISSUE TITLE
support multiple unique key (composite primary key)

### ISSUE THREAD

**Issue by imfaridz** [autotraderuk/dbt-dry-run#18]
Hi,

I encounter this issue when execute dbt-dry-run to a table that has multiple unique key or composite primary key:

```pydantic.error_wrappers.ValidationError: 1 validation error for Manifest
nodes -> model.dbt_re_data_test.table_name -> config -> unique_key
  str type expected (type=type_error.str)

```

need support to be able to include list type for multiple column unique_key

**Comment by connor-charles** [comment]
Hey @imfaridz,

Thanks for raising an issue. Looks like support for this was added in dbt-core 1.1 in [this PR
](https://github.com/dbt-labs/dbt-core/pull/4618)

Setting `unique_key` as a list is only supported for incremental tables so this issue will be fairly easy to fix as  only the [snapshot_runner
](https://github.com/autotraderuk/dbt-dry-run/blob/main/dbt_dry_run/node_runner/snapshot_runner.py) uses `unique_key` when validating the model config.

I will raise a PR to update our pydantic model schema

**Comment by connor-charles** [comment]
Will do a patch release for this sometime this week now the PR is merged

**Comment by imfaridz** [comment]
thanks for the support @connor-charles !
