### ISSUE TITLE
Defered State

### ISSUE THREAD

**Issue by ce-tcholewik** [autotraderuk/dbt-dry-run#22]
Hi, so after poking around the source code, I can't see evidence that anyone considered using DBT's defer flag. I wonder if anyone tried incorporating it or if this was considered a bad idea.

I'd be happy to make a PR to include it, but I want to get some context first; previous attempts/discussions I may have missed. Also, I realize you are using dbt internals, so it might not be a good practice to make code here more dependent on dbt's code, and in this case, I think this would be required.

**Comment by connor-charles** [comment]
Hey @ce-tcholewik thanks for raising an issue!

I hadn't heard of the `defer` CLI flag in dbt before. Looks very useful for development workflows. However I am struggling to see what problem it would solve by adding it to the dry runner though? Can you elaborate on your use case?

If you wanted to dry run a dbt project that had been compiled with `defer` I think that would be possible:

```
# compile the manifest with deferred references
dbt compile --defer
# Run the dry runner
dbt-dry-run 
```

Although the dry runner works best when you run it against your production environment if you are using it in CI.
