### ISSUE TITLE
Proposal for `dry-run` feature in dbt-core

### ISSUE THREAD

**Issue by aaronsteers** [autotraderuk/dbt-dry-run#33]
I've referenced this `dbt-dry-run` tool in a feature request to dbt-core.

Would love to request thoughts, feedback, and upvotes there on the discussion:

- https://github.com/dbt-labs/dbt-core/discussions/6989

Sidenote: we're currently in progress of adding this to Meltano Hub - so a big thanks to the contributors and maintainers of this package.

- https://github.com/meltano/hub/pull/1164

**Comment by connor-charles** [comment]
I am going to close this as I don't think this requires any more action.

Although I would welcome a PR to reference the Meltano plugin in the `dbt-dry-run` README. Something like a `Using with Meltanto` section and linking to the meltano plugin's homepage?
