### ISSUE TITLE
Support BigQuery RANGE type

### ISSUE THREAD

**Issue by rickgingrich** [autotraderuk/dbt-dry-run#65]
Dry-running dbt models that use the new BigQuery [`RANGE` data type](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#range_type) result in an error:

```
UnknownSchemaException: BigQuery dry run field 'time_range' returned unknown column types: 'RANGE' is not a valid 
BigQueryFieldType.If you think this column type is valid then raise an issue on GitHub
```
Support for the `RANGE` type was recently released in the official BigQuery Python Client: https://github.com/googleapis/python-bigquery/releases/tag/v3.22.0

**Comment by ccharlesgb** [comment]
There will be a release soon to support dbt 1.8 so this will probably go out with that. #68
