### ISSUE TITLE
Support dbt-core / dbt-bigquery 1.8

### ISSUE THREAD

**Issue by w1mvy** [autotraderuk/dbt-dry-run#68]
dbt-core 1.8 has been released,  so I think need to follow.

**Comment by ccharlesgb** [comment]
GH Action is failing for the 1.8 support: https://github.com/autotraderuk/dbt-dry-run/actions/runs/9187931611
Not sure why as the integration tests run locally. Could be something to do with env vars and it not being able to find the service account key.

**Comment by ccharlesgb** [comment]
Sorry for the delay I think this issue has now been fixed so 1.8 support is now available
